version: "3"
services:
  # certbot:
  #   image: certbot/certbot
  # volumes:
  #   - ./data/certbot/conf:/etc/letsencrypt
  #   - ./data/certbot/www:/var/www/certbot

  nginx:
    restart: always
    image: wongzq/pendemic-nginx
    ports:
      - "80:80"
    # volumes:
    #   - ./data/certbot/conf:/etc/letsencrypt
    #   - ./data/certbot/www:/var/www/certbot

  app:
    restart: always
    image: wongzq/pendemic-app
    expose:
      - 3000
    env_file:
      - /etc/.env.staging
