# STAGE 1
FROM node:13.12.0-alpine as build

WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# STAGE 2
FROM node:13.12.0-alpine

WORKDIR /usr/app
COPY package*.json ./
RUN npm install --production

COPY --from=build /usr/app/dist ./dist

ENV NODE_ENV=staging
COPY .env.staging .

EXPOSE 3000
CMD node dist/server.js