SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `chapter`;
DROP TABLE IF EXISTS `character`;
DROP TABLE IF EXISTS `characterrelationship`;
DROP TABLE IF EXISTS `plot`;
DROP TABLE IF EXISTS `plotpoint`;
DROP TABLE IF EXISTS `plotpointchapter`;
DROP TABLE IF EXISTS `plotpointcharacter`;
DROP TABLE IF EXISTS `plotpointsetting`;
DROP TABLE IF EXISTS `setting`;
DROP TABLE IF EXISTS `story`;
DROP TABLE IF EXISTS `writer`;

SET FOREIGN_KEY_CHECKS = 1;
